Feature budget and categories
AleksandrasMaliuginas/SmartSaver pull request #35
Opened 2020-10-28 19:05 UTC by imila254

Income and outcome calculation in main window.

2020-10-28 19:11 UTC, barkas90 approved these changes

2020-10-28 19:38 UTC, AleksandrasMaliuginas requested changes

2020-10-28 19:38 UTC, AleksandrasMaliuginas commented on Desktop/Main.cs
> +            IncomeAndOutcomeCalculation(_transactionList);
It's not necessary to pass a transaction list because it is a property of a class.

2020-10-28 19:38 UTC, AleksandrasMaliuginas commented on Models/Tip.cs
> +        }
What is this constructor for?

2020-10-29 06:28 UTC, imila254 commented on Models/Tip.cs
> +        }
Going to remove this.

2020-10-29 06:49 UTC, AleksandrasMaliuginas approved these changes
Perfecto

2020-10-29 07:11 UTC, AleksandrasMaliuginas approved these changes

2020-10-29 11:23 UTC, merged