Add file reading and writing
AleksandrasMaliuginas/SmartSaver pull request #9
Opened 2020-10-01 05:37 UTC by sk057

2020-10-01 10:33 UTC, imila254 approved these changes

2020-10-06 08:42 UTC, AleksandrasMaliuginas requested changes
Move to separate class

2020-10-06 08:46 UTC, imila254 approved these changes

2020-10-07 07:16 UTC, AleksandrasMaliuginas approved these changes
A way better! Later on FileManager should be moved to other namespace, however, because it is not a part of desktop UI environment.

2020-10-07 18:41 UTC, merged